export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Carla Perez",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Osvaldo Riquelme",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Alejandro Carballo",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Julieta Ibarra",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Yanina Lopez",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Camila Juarez",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Pedro Zapata",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Lourdes Sanchez",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Luisa Pavez",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Romina Ulloa",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Amor por todos, odio por ninguno.",
    photo: "post/1.jpeg",
    date: "5 min atras",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpeg",
    date: "15 min atras",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Cada momento es un nuevo comienzo.",
    photo: "post/3.jpeg",
    date: "1 hora atras",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpeg",
    date: "4 horas atras",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.jpeg",
    date: "5 horas atras",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpeg",
    date: "1 dia atras",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Nunca te arrepientas de nada que te haga sonreír.",
    photo: "post/7.jpeg",
    date: "2 dias atras",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpeg",
    date: "3 dias atras",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Cambia el mundo siendo tú mismo.",
    photo: "post/9.jpeg",
    date: "5 dias atras",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "1 semana atras",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
